### ISSUE TITLE
[Sonar] Remove this expression which always evaluates to "false" in `src/main/java/org/trebol/jpa/services/crud/BillingTypesJpaCrudServiceImpl.java`

### ISSUE THREAD

**Issue by mepox** [trebol-ecommerce/trebol-backend-monolith#217]
- [Source Sonar issue URL](https://sonarcloud.io/project/issues?issues=AYKvHFjjl4ZcazHMfJ5O&open=AYKvHFjjl4ZcazHMfJ5O&id=trebol-ecommerce_spring-boot-backend)
- Issue type: `Code Smell`
- Severity: `Major`
- Technical debt: `5min effort`

**Comment by bglamadrid** [comment]
Please fix this issue using a `StringUtils.isBlank` call. It is a recent custom to have it spare us of this very repeating pattern.

So instead of doing as

https://github.com/trebol-ecommerce/spring-boot-backend/blob/46dc761fbb61d4d6a5cab868c66b0c8cbc708a43/src/main/java/org/trebol/jpa/services/crud/BillingTypesJpaCrudServiceImpl.java#L57

Please do as

```java
if (StringUtils.isBlank(name)) {
```

**Comment by bglamadrid** [comment]
This issue was probably closed after merging #229
